/*
|| Partitioning of CONTRACT_ALL
|| Created for Zain Sudan
|| Author: Serge Shmygelskyy aka Shmyg
|| mailto: serge.shmygelskyy@gmail.com // sergiy.shmygelskyy@ericsson.com
||
|| $Log: contract_all.sql,v $
|| Revision 1.1  2013/08/14 14:20:58  shmyg
|| First completely working version of redefinition scrips for ZAS
||
||
*/

VAR num_errors NUMBER;

ALTER TABLE sysadm.contract_all PARALLEL;

BEGIN
DBMS_REDEFINITION.CAN_REDEF_TABLE
	(
	'SYSADM',
	'CONTRACT_ALL',
	DBMS_REDEFINITION.CONS_USE_PK
	);
END;
/

CREATE TABLE sysadm.int_contract_all
	(
	CO_ID			NUMBER(*,0) NOT NULL,
	CUSTOMER_ID		NUMBER(*,0) NOT NULL,
	TYPE			VARCHAR2(1),
	PLCODE			NUMBER(*,0),
	SCCODE			NUMBER(*,0),
	SUBM_ID			NUMBER(*,0),
	CO_SIGNED		DATE,
	CO_EQU_TYPE		VARCHAR2(20),
	CO_REP_BILL		VARCHAR2(40),
	CO_REP			VARCHAR2(40),
	CO_REP_BILL_IDNO	VARCHAR2(30),
	CO_REP_IDNO		VARCHAR2(30),
	CO_INSTALLED		DATE,
	CO_ARCHIVE		VARCHAR2(1),
	CO_DIR_ENTRY		VARCHAR2(1),
	CO_OPERATOR_DIR		VARCHAR2(1),
	CO_PSTN_DIR		VARCHAR2(1),
	CO_ASS_SERV		VARCHAR2(1),
	CO_ASS_EQU		VARCHAR2(1),
	CO_CRD_CHECK		VARCHAR2(1),
	CO_CRD_CHK_END		DATE,
	CO_CRD_CHK_START	DATE,
	CO_CRD_CLICKS		NUMBER(*,0),
	CO_CRD_CLICKS_DAY	NUMBER(*,0),
	CO_CRD_DAYS		NUMBER(*,0),
	CO_COMMENT		VARCHAR2(60),
	CO_RESERVED		DATE,
	CO_EXPIR_DATE		DATE,
	CO_ACTIVATED		DATE,
	CO_ENTDATE		DATE NOT NULL,
	CO_MODDATE		DATE,
	CO_USERLASTMOD		VARCHAR2(16),
	TMCODE			NUMBER(*,0),
	TMCODE_DATE		DATE,
	CO_CRD_D_TR1		NUMBER(*,0),
	CO_CRD_D_TR2		NUMBER(*,0),
	CO_CRD_D_TR3		NUMBER(*,0),
	CO_CRD_P_TR1		NUMBER(*,0),
	CO_CRD_P_TR2		NUMBER(*,0),
	CO_CRD_P_TR3		NUMBER(*,0),
	CONTRACT_ID_LDC		NUMBER(*,0),
	PENDING_CONTRACT_ID_LDC	NUMBER(*,0),
	CONTRACT_ID_LEC		NUMBER(*,0),
	PENDING_CONTRACT_ID_LEC	NUMBER(*,0),
	CO_REQUEST		NUMBER(*,0),
	DEALER_ID		NUMBER(*,0),
	NOT_VALID		VARCHAR2(1),
	ARPCODE			NUMBER(*,0),
	CO_ADDR_ON_IBILL	VARCHAR2(1),
	CO_CRD_AMOUNT		FLOAT(126),
	CO_CRD_AMOUNT_DAY	FLOAT(126),
	PRODUCT_HISTORY_DATE	DATE,
	CO_CONFIRM		VARCHAR2(1),
	CO_EXT_CSUIN		VARCHAR2(50),
	TRIAL_END_DATE		DATE,
	CO_IB_CDR_FLAG		VARCHAR2(1),
	CURRENCY		NUMBER(*,0),
	REC_VERSION		NUMBER(*,0) DEFAULT 0 NOT NULL,
	AN_PACKAGE_ID		NUMBER(*,0),
	CO_REL_TYPE		VARCHAR2(1),
	PENDING_TMCODE		NUMBER(*,0),
	CONTRACT_TEMPLATE	VARCHAR2(1),
	CO_CODE			VARCHAR2(30) NOT NULL,
	BUSINESS_UNIT_ID	NUMBER(*,0) NOT NULL,
	DESCRIPTION		VARCHAR2(100),
	AGREEMENT_TYPE		VARCHAR2(2),
	EXT_PRODUCT_ID		NUMBER(*,0),
	REMOTE_PLCODE		NUMBER(*,0),
	ECCODE			NUMBER(*,0),
	HPLMN_BID_GROUP_ID	NUMBER(*,0),
	VPLMN_BID_GROUP_ID	NUMBER(*,0),
	HOME_PARTY_ID		NUMBER(*,0) NOT NULL,
	CONTRACT_TYPE_ID	NUMBER(*,0) NOT NULL,
	TRIAL_START_DATE	DATE,
	FOH_AGGREGATION_FLAG	CHAR(1),
	GL_ACC_PACK_ID		NUMBER(*,0),
	CDS_BILL_MEDIUM		NUMBER(*,0) DEFAULT NULL,
	CDS_GENERATION		CHAR(1),
	CHARGE_PART_NUM		NUMBER(*,0),
	CH_STATUS		CHAR(1) DEFAULT 'o',
	SVP_FILE		VARCHAR2(5),
	CHARGE_PER_ADJ_REF	CHAR(1) DEFAULT NULL,
	NEXT_CUTOFF_DATE	DATE,
	LAST_CUTOFF_DATE	DATE,
	LAST_CHARGE_DATE	DATE,
	LAST_NOTICE_DATE	DATE,
	NOT_BILL_MEDIUM		NUMBER(*,0),
	CHARGE_START_DATE	DATE,
	EARLIEST_END_DATE	DATE,
	COMMON_REF_DATA_IND	CHAR(1),
	CONTRACT_LANGUAGE	NUMBER(*,0) DEFAULT NULL,
	PENDING_LANGUAGE	NUMBER(*,0),
	RR_CANDIDATE		CHAR(1),
	CH_STATUS_VALIDFROM	DATE,
	SDP_ID			NUMBER(*,0),
	TRANSACTION_ID		NUMBER(*,0),
	IVR_BARRING_TIME	DATE
	)
PARTITION BY RANGE (co_id)
	(  
	PARTITION contract_all_1 VALUES LESS THAN (1000001),
	PARTITION contract_all_2 VALUES LESS THAN (2000001),
	PARTITION contract_all_3 VALUES LESS THAN (3000001),
	PARTITION contract_all_4 VALUES LESS THAN (4000001),
	PARTITION contract_all_5 VALUES LESS THAN (5000001),
	PARTITION contract_all_6 VALUES LESS THAN (6000001),
	PARTITION contract_all_7 VALUES LESS THAN (7000001),
	PARTITION contract_all_8 VALUES LESS THAN (8000001),
	PARTITION contract_all_9 VALUES LESS THAN (9000001),
	PARTITION contract_all_10 VALUES LESS THAN (10000001),
	PARTITION contract_all_11 VALUES LESS THAN (11000001),
	PARTITION contract_all_12 VALUES LESS THAN (12000001),
	PARTITION contract_all_13 VALUES LESS THAN (13000001),
	PARTITION contract_all_14 VALUES LESS THAN (14000001),
	PARTITION contract_all_15 VALUES LESS THAN (15000001),
	PARTITION contract_all_16 VALUES LESS THAN (16000001),
	PARTITION contract_all_17 VALUES LESS THAN (17000001),
	PARTITION contract_all_18 VALUES LESS THAN (18000001),
	PARTITION contract_all_19 VALUES LESS THAN (19000001),
	PARTITION contract_all_20 VALUES LESS THAN (20000001),
	PARTITION contract_all_21 VALUES LESS THAN (21000001),
	PARTITION contract_all_22 VALUES LESS THAN (MAXVALUE)
	)
TABLESPACE shmyg_ts
INITRANS 32
PCTFREE 10
STORAGE
	(
	INITIAL	16M
	NEXT	16M
	)
NOLOGGING;

/*
BEGIN
DBMS_REDEFINITION.START_REDEF_TABLE
	(
	'SYSADM',
	'CONTRACT_ALL',
	'INT_CONTRACT_ALL',
	col_mapping => NULL,
	options_flag => DBMS_REDEFINITION.CONS_USE_PK
	);
END;
/

CREATE	UNIQUE INDEX sysadm.int_pk_contract_all
ON	sysadm.int_contract_all
	(
	co_id
	)
TABLESPACE shmyg_ts
INITRANS 32
STORAGE
	(
	INITIAL	4M
	NEXT	4M
	)
NOLOGGING
PARALLEL
LOCAL;

BEGIN
DBMS_REDEFINITION.COPY_TABLE_DEPENDENTS
	(
	'SYSADM',
	'CONTRACT_ALL',
	'INT_CONTRACT_ALL',
	1,
	TRUE,
	TRUE,
	TRUE,
	TRUE,
	:num_errors
	);
END;
/

BEGIN
DBMS_REDEFINITION.SYNC_INTERIM_TABLE
	(
	'SYSADM',
	'CONTRACT_ALL',
	'INT_CONTRACT_ALL'
	);
END;
/

BEGIN
DBMS_REDEFINITION.FINISH_REDEF_TABLE
	(
	'SYSADM',
	'CONTRACT_ALL',
	'INT_CONTRACT_ALL'
	);
END;
/

DROP	TABLE sysadm.int_contract_all;

BEGIN
DBMS_STATS.GATHER_TABLE_STATS
	(
	'SYSADM',
	'CONTRACT_ALL',
	degree => 32,
	method_opt => 'for all columns size auto',
	estimate_percent => 10,
	granularity => 'ALL',
	cascade => TRUE
	);
END;
/

ALTER	INDEX sysadm.int_pk_contract_all
RENAME	TO pk_contract_all;

ALTER TABLE sysadm.contract_all LOGGING;
ALTER TABLE sysadm.contract_all NOPARALLEL;
ALTER INDEX sysadm.pk_contract_all NOPARALLEL;
*/
